server:
  port: 8080
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: crypto-tax-calculator
  
  profiles:
    active: development
  
  datasource:
    url: jdbc:h2:mem:cryptotax
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console

# CORS Configuration
cors:
  allowed:
    origins: ${CORS_ORIGINS:http://localhost:3000}

# Logging
logging:
  level:
    com.cryptotax: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Management
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: docker
  
  datasource:
    url: jdbc:h2:mem:cryptotax
    username: sa
    password: 
    driver-class-name: org.h2.Driver

logging:
  level:
    com.cryptotax: INFO
    org.springframework.security: WARN